[package]
name = "nexsock"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx-utils = { version = "1.0.0-2", default-features = false, features = ["sqlite"], registry = "gitea" }
sqlx = { version = "0.8.3", features = ["sqlite", "macros", "chrono", "runtime-tokio"] }
tokio = { version = "1.43", features = ["full"] }
thiserror = "2.0.11"
tempfile = "3.15.0"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-core = "0.1.33"
tosic-utils = { version = "0.2.3", features = ["env", "dotenv", "tracing"], registry = "gitea" }
git2 = { version = "0.20.0" }
serde = { version = "1.0.215", features = ["derive"] }
paste = "1.0.15"
