[registries.gitea]
index = "sparse+https://reasonably-happy-moose.ngrok-free.app/api/packages/tosic.killer/cargo/"

# We only enable tokio_taskdump on Linux targets since it's not supported on Mac
[build]
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]

[target.x86_64-unknown-linux-musl]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]

[target.aarch64-unknown-linux-musl]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "tokio_taskdump"]
