//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

/// Re-exports important entities and enums for easier use.
pub mod prelude;

/// Defines the `Service` entity and related components.
pub mod service;
/// Defines the `ServiceConfig` entity and related components.
pub mod service_config;
/// Defines the `ServiceDep` entity and related components.
pub mod service_dep;
/// Defines the `ServiceDependency` entity and related components.
pub mod service_dependency;
/// Defines the `ServiceRecord` entity and related components.
pub mod service_record;
